{ colors }:

let
  inherit (colors.withHashtag)
    base00
    base01
    base02
    base03
    base04
    base05
    base06
    base08
    base09
    base0A
    base0B
    base0C
    base0D
    base0E
    ;
in
# css
''
  /* Generated by Stylix. This is a complete override layer on top of
     IDA's dark theme, so widgets that need IDA-specific qproperties do
     not fall back to the built-in light/default colors. */

  @def stylix_highlight rgba(128, 128, 0, 0.35);
  @def stylix_highlight_2 rgba(128, 64, 0, 0.35);
  @def stylix_highlight_3 rgba(128, 0, 128, 0.35);
  @def stylix_highlight_4 rgba(0, 128, 128, 0.35);
  @def stylix_highlight_5 rgba(128, 0, 0, 0.35);
  @def stylix_highlight_6 rgba(0, 128, 0, 0.35);
  @def stylix_highlight_7 rgba(0, 64, 128, 0.35);
  @def stylix_highlight_8 rgba(128, 128, 128, 0.35);

  *
  {
      color: ${base05};
      background-color: ${base00};
      selection-color: ${base00};
      selection-background-color: ${base0D};
  }

  DockWidgetTitle,
  DockAreaDragTitle
  {
      background-color: ${base01};
      border: 1px solid ${base03};
  }

  DockWidgetTitle[active="true"]
  {
      color: ${base06};
      background-color: ${base02};
  }

  chooser_widget_t,
  standalone_dirtree_widget_t
  {
      qproperty-highlight-bg-default: ${base02};
      qproperty-highlight-bg-selected: ${base0D};
      qproperty-cut-text-color-default: ${base03};
      qproperty-cut-text-color-selected: ${base04};
  }

  log_widget_t
  {
      color: ${base05};
      background-color: ${base00};
  }

  text_area_t
  {
      qproperty-keyword1-fg: ${base0D};
      qproperty-keyword2-fg: ${base0E};
      qproperty-keyword3-fg: ${base08};
      qproperty-string-fg: ${base0B};
      qproperty-comment-fg: ${base03};
      qproperty-preprocessor-fg: ${base0A};
      qproperty-user1-fg: ${base0C};
  }

  TChooser,
  CLIWidget,
  TForm
  {
      color: ${base05};
      background-color: ${base00};
      qproperty-header-color: ${base06};
  }

  QMenuBar,
  QMenu,
  QToolBar,
  QStatusBar,
  QTabWidget,
  QTabBar::tab,
  QWidget
  {
      color: ${base05};
      background-color: ${base00};
  }

  QMenu::item:selected,
  QTabBar::tab:selected,
  QTreeView::item:selected,
  QListView::item:selected,
  QTableView::item:selected
  {
      color: ${base00};
      background-color: ${base0D};
  }

  QLineEdit,
  QTextEdit,
  QPlainTextEdit,
  QComboBox,
  QSpinBox,
  QTreeView,
  QListView,
  QTableView
  {
      color: ${base05};
      background-color: ${base01};
      border: 1px solid ${base03};
  }

  QPushButton
  {
      color: ${base05};
      background-color: ${base01};
      border: 1px solid ${base03};
      padding: 3px;
  }

  QPushButton:hover
  {
      border-color: ${base0D};
  }

  CustomIDAMemo
  {
      border: none;

      qproperty-line-fg-default: ${base05};
      qproperty-line-fg-regular-comment: ${base03};
      qproperty-line-fg-repeatable-comment: ${base04};
      qproperty-line-fg-automatic-comment: ${base03};
      qproperty-line-fg-insn: ${base06};
      qproperty-line-fg-dummy-data-name: ${base0A};
      qproperty-line-fg-regular-data-name: ${base0A};
      qproperty-line-fg-demangled-name: ${base0C};
      qproperty-line-fg-punctuation: ${base04};
      qproperty-line-fg-charlit-in-insn: ${base0B};
      qproperty-line-fg-strlit-in-insn: ${base0B};
      qproperty-line-fg-numlit-in-insn: ${base09};
      qproperty-line-fg-void-opnd: ${base08};
      qproperty-line-fg-code-xref: ${base0D};
      qproperty-line-fg-data-xref: ${base0C};
      qproperty-line-fg-code-xref-to-tail: ${base09};
      qproperty-line-fg-data-xref-to-tail: ${base0A};
      qproperty-line-fg-error: ${base08};
      qproperty-line-fg-line-prefix: ${base04};
      qproperty-line-fg-opcode-byte: ${base03};
      qproperty-line-fg-extra-line: ${base0E};
      qproperty-line-fg-alt-opnd: ${base0E};
      qproperty-line-fg-hidden: ${base03};
      qproperty-line-fg-libfunc: ${base0C};
      qproperty-line-fg-locvar: ${base09};
      qproperty-line-fg-dummy-code-name: ${base0A};
      qproperty-line-fg-asm-directive: ${base0E};
      qproperty-line-fg-macro: ${base0E};
      qproperty-line-fg-strlit-in-data: ${base0B};
      qproperty-line-fg-charlit-in-data: ${base0B};
      qproperty-line-fg-numlit-in-data: ${base09};
      qproperty-line-fg-keyword: ${base0D};
      qproperty-line-fg-register-name: ${base0D};
      qproperty-line-fg-import-name: ${base0E};
      qproperty-line-fg-segment-name: ${base0A};
      qproperty-line-fg-dummy-unknown-name: ${base0A};
      qproperty-line-fg-code-name: ${base0D};
      qproperty-line-fg-unknown-name: ${base05};
      qproperty-line-fg-collapsed-line: ${base0C};
      qproperty-line-bg-default: ${base00};
      qproperty-line-bg-selected: ${base02};
      qproperty-caret: ${base06};
      qproperty-line-pfx-libfunc: ${base0C};
      qproperty-line-pfx-func: ${base0D};
      qproperty-line-pfx-insn: ${base08};
      qproperty-line-pfx-data: ${base0A};
      qproperty-line-pfx-unexplored: ${base03};
      qproperty-line-pfx-extern: ${base0E};
      qproperty-line-pfx-current-line: ${base0A};
      qproperty-line-pfx-current-item: ${base09};
      qproperty-line-pfx-lumina: ${base0B};
      qproperty-graph-bg-top: ${base00};
      qproperty-graph-bg-bottom: ${base00};
      qproperty-graph-node-title-normal: ${base01};
      qproperty-graph-node-title-selected: ${base02};
      qproperty-graph-node-title-current: ${base03};
      qproperty-graph-node-frame-group: ${base0A};
      qproperty-graph-node-shadow: ${base00};
      qproperty-graph-node-high1: ${base0B};
      qproperty-graph-node-high2: ${base08};
      qproperty-graph-node-foreign: ${base08};
      qproperty-graph-edge-normal: ${base0D};
      qproperty-graph-edge-yes: ${base0B};
      qproperty-graph-edge-no: ${base08};
      qproperty-graph-edge-high: ${base0E};
      qproperty-graph-edge-selected: ${base0A};
      qproperty-graph-node-frame-selected: ${base0A};
      qproperty-line-fg-patched-bytes: ${base08};
      qproperty-line-fg-unsaved-changes: ${base09};
      qproperty-line-bg-highlight: ''${stylix_highlight};
      qproperty-line-bg-highlight-2: ''${stylix_highlight_2};
      qproperty-line-bg-highlight-3: ''${stylix_highlight_3};
      qproperty-line-bg-highlight-4: ''${stylix_highlight_4};
      qproperty-line-bg-highlight-5: ''${stylix_highlight_5};
      qproperty-line-bg-highlight-6: ''${stylix_highlight_6};
      qproperty-line-bg-highlight-7: ''${stylix_highlight_7};
      qproperty-line-bg-highlight-8: ''${stylix_highlight_8};
      qproperty-line-bg-bpt-enabled: ${base08};
      qproperty-line-bg-bpt-disabled: ${base0B};
      qproperty-line-bg-bpt-unavailable: ${base09};
      qproperty-bookmark-star-outline: ${base0A};
  }

  CustomIDAMemo[debugging="true"]
  {
      qproperty-line-bg-default: ${base01};
  }

  CustomIDAMemo[hints="true"]
  {
      qproperty-line-bg-default: ${base01};
  }

  TCpuRegs
  {
      background-color: ${base01};
      qproperty-register-defined: ${base06};
      qproperty-register-changed: ${base0A};
      qproperty-register-edited: ${base09};
      qproperty-register-unavailable: ${base03};
  }

  TCpuRegs ui_label_t
  {
      color: ${base05};
  }

  TextArrows
  {
      qproperty-jump-in-function: ${base02};
      qproperty-jump-external-to-function: ${base0C};
      qproperty-jump-under-cursor: ${base0A};
      qproperty-jump-target: ${base0B};
      qproperty-register-target: ${base08};
  }

  navband_t
  {
      qproperty-lib-function: ${base0C};
      qproperty-function: ${base0A};
      qproperty-code: ${base08};
      qproperty-data: ${base0A};
      qproperty-undefined: ${base03};
      qproperty-extern: ${base0E};
      qproperty-lumina-function: ${base0B};

      qproperty-hl-lib-function: ${base0C};
      qproperty-hl-function: ${base0A};
      qproperty-hl-code: ${base08};
      qproperty-hl-data: ${base06};
      qproperty-hl-undefined: ${base0A};
      qproperty-hl-extern: ${base0E};
      qproperty-hl-lumina-function: ${base0B};

      qproperty-hl-outline: ${base0C};
      qproperty-error: ${base08};
      qproperty-gap: ${base02};
      qproperty-cursor: ${base0B};
      qproperty-auto-analysis-cursor: ${base09};
  }

  xref_tree_t
  {
      qproperty-function-name-color:        ${base0D};
      qproperty-library-function-color:     ${base0C};
      qproperty-imported-function-color:    ${base0E};
      qproperty-data-name-color:            ${base0A};
      qproperty-regular-data-name-color:    ${base0A};
      qproperty-string-literal-color:       ${base0B};
      qproperty-data-string-color:          ${base0B};
      qproperty-numeric-constant-color:     ${base09};
      qproperty-data-numeric-color:         ${base09};
      qproperty-keyword-color:              ${base0D};
      qproperty-symbol-color:               ${base04};
      qproperty-register-color:             ${base0D};
      qproperty-local-name-color:           ${base09};
      qproperty-code-reference-color:       ${base0D};
      qproperty-data-reference-color:       ${base0C};
      qproperty-prefix-color:               ${base04};
      qproperty-tree-background-color:      ${base00};
      qproperty-search-match-color:         ''${stylix_highlight};
  }

  viewer_t
  {
      qproperty-node-bg-import: ${base0E};
      qproperty-node-bg-code: ${base0D};
      qproperty-node-bg-data: ${base0B};
      qproperty-node-bg-default: ${base03};
      qproperty-node-border: ${base05};
      qproperty-node-text: ${base00};
      qproperty-edge-default: ${base04};
      qproperty-edge-highlighted: ${base0D};
      qproperty-viewer-bg: ${base00};
  }

  viewer_t QWidget
  {
      background-color: ${base00};
  }
''
